### PR TITLE
Added unbrush and brush function to render.js

### PR DESCRIPTION
**Pull request by dehli**
Hi! I've added two functions that can be used to programmatically brush or unbrush elements. What are your thoughts on these implementations? I think it could be something that's useful.

Thanks!

### CODE REVIEW

**Comment by mcwillso** [comment]
@delhi I am wondering if [highlight](https://github.com/syntagmatic/parallel-coordinates#parcoords_highlight) is what you wanted? Programmatically setting the brushed elements like you suggest without setting the brush extents on the axis might cause some user experience issues.

Let me checkout your fork.

**Comment by dehli** [comment]
Ahh, that's a good point. i was thinking of completely disabling the brush extents and only using these programmatically. My thought was that I'd have a table like [this](http://syntagmatic.github.io/parallel-coordinates/examples/table.html) with checkboxes on each row. Then you could check/uncheck the row to either hide or show it.

If brush extents were enabled, then unbrushing an element could possible modify the brush extent? Maybe brush/unbrush would only work when you have the ability to add multiple brush extents or if they're completely disabled.

Hope this makes sense.

**Comment by mcwillso** [comment]
@dehli What functionality is missing from the highlight functions to accomplish that?

**Comment by dehli** [comment]
I liked using unbrush/brush so that the background lines wouldn't show up. Let me further investigate using highlight though. It might be able to work. Thanks!

**Comment by dehli** [comment]
I'm going to retry this in another branch.

**Pull request closed without merging**
