### PR TITLE
Fix updateAxes: it wasnt using dimensionTitles

### PR DESCRIPTION
**Pull request by lukaw3d**

### CODE REVIEW

**Comment by syntagmatic** [comment]
It looks like `createAxes` uses the dimension aliases, but `updateAxes` does not. Looks like a good fix to me.

**Comment by lukaw3d** [comment]
Live demo: http://syntagmatic.github.io/parallel-coordinates/examples/titles.html
Running the following commands in console, different axis titles are created:
```js
parcoords.updateAxes();
parcoords.createAxes();
```

**Comment by lukaw3d** [comment]
This appears to be manually merged into master (https://github.com/syntagmatic/parallel-coordinates/commit/51c9c0bda9b2c30d1f5a57e585083452ab5a633f)

**Comment by syntagmatic** [comment]
Thanks Luka!

**Comment by bbroeksema** [comment]
My bad, yes merged this manually, keeps the history nicely linearly. Thanks again for the fix.

**Pull request closed without merging**
