### PR TITLE
Fix for not cleaning the highlight canvas on 'all-in'  render call.

### PR DESCRIPTION
**Pull request by shodanjr**
Potential fix for syntagmatic/parallel-coordinates#86.

### CODE REVIEW

**Comment by shodanjr** [comment]
Please disregard this PR for the time being, I messed up in a one-line fix.

**Comment by shodanjr** [comment]
Updated with actual fix.

**Comment by bbroeksema** [comment]
Perfect! Can you clean up the pull request (i.e. create a new one) with only the commit for the fix? Otherwise I can just commit the fix myself and put your name in the comments.... As you wish.

**Comment by shodanjr** [comment]
Alright, let me make a clean version of the repo.

**Pull request closed without merging**
