### PR TITLE
Added a function to reorder the axes

### PR DESCRIPTION
**Pull request by KPWhiver**
Added pc.reorder() which receives data values for the axes and orders the axes based on the visual height of those data values.

### CODE REVIEW

**Comment by bbroeksema** [comment]
Full disclosure, KPWhiver is interning at our place. We actually need this function, so I'll go on and merge it.

**Comment by bbroeksema** [comment]
@KPWhiver before the merge though, you'll have to add the required change to the correct file (src/axis.js) and run make afterwards. Otherwise this change gets lost.

**Comment by julianheinrich** [comment]
Can we use another name for that function? You can reorder axes in a
million ways, it might be confusing to use the 'visual height' (can you
explain to me what this means?)

**Comment by bbroeksema** [comment]
@julianheinrich Good point :). Actually, a more generic approach would be one similar to the current brushing mechanism. If you have any suggestions for a ad-interim name for the function, I'll try to squeeze some time in to properly refactor this functionality in a more extensible way.

**Comment by syntagmatic** [comment]
An example of similar functionality [here](http://bl.ocks.org/syntagmatic/raw/3290392/). Click one of the foods in the sample of 25 entries to sort axes by visual height of a datum.

**Comment by bbroeksema** [comment]
@syntagmatic yep that's pretty much it. We generalize a bit on it and implented sorting based on various metrics of a selection (e.g. average, median, std dev) in order to highlight different kinds of patterns. Still work in progress but looks interesting already.

**Comment by julianheinrich** [comment]
@bbroeksema  ok so you're computing an average (or median, ...) per axes and sort in ascending or descending order?

I'd love to see the reordering API to be similar to your brushing approach, something like:

    pc.reorder("median", {order: "ascending"})

Maybe we should even add *axis to that, because one might also want to reorder lines (or samples for that matter, as we also support curves and possibly other geometry in the future):

    pc.reorderAxes("median", {order: "ascending"})
    pc.reorderSamples("dimension", {name: "cylinders"})

The latter would, e.g., order lines in the order of the cylinders-dimension (in the cars dataset).
What do you think?

**Pull request closed without merging**
