### PR TITLE
Added flipAxes and animationTime

### PR DESCRIPTION
**Pull request by dehli**
This adds `flipAxes` which can be called like:

`parcoords.flipAxes(['x', 'z']);`

Additionally, it adds `animationTime` which configures how long it takes for the axes to flip on double click. 

`parcoords.animationTime(500);`

The whitespace changes are either trailing space that's been removed or replacing tabs with spaces.

### CODE REVIEW

**Comment by mcwillso** [comment]
@dehli don't forget to commit the files that you edit i.e. don't edit the d3.parcoords.js file directly.  Run ```make clean``` then ```make``` before committing.

**Comment by dehli** [comment]
Oops, thanks @mcwillso! I've just been modifying `d3.parcoords.js` directly. Didn't notice that in the readme.

**Comment by syntagmatic** [comment]
Someday we should consider moving to the new d3 plugin pattern, but it would be a pretty big refactor to get there. The `make` workflow is a bit cumbersome, especially since the separate files aren't cleanly separated modules (they use the same namespace). 

https://bost.ocks.org/mike/d3-plugin/

Thanks again @dehli and @mcwillso!

**Comment by dehli** [comment]
Thanks for the link @syntagmatic! I will look into that when I have some time. I'll go ahead and merge this pull request then.

**Pull request merged**
