### PR TITLE
Flip axis

### PR DESCRIPTION
**Pull request by dehli**
Good morning, 

With this pull request, you can call `flipAxes()` in order to flip the axis without any animation (so you can call it right when it's rendered).

`parcoords.flipAxes(["x", "y"]);`

~~The changes to `bower.json` and `package.json` are in #287. If that was accepted first, then I think they'll automatically be removed from this one. I accidentally pushed them to my fork's master which is why they're here as well.~~

Any thoughts about this? I updated the `README` to show an example. I also added a color function example because I saw a todo for it.

Thanks!

### CODE REVIEW

**Comment by syntagmatic** [comment]
Also a thought on the `transitionTime` variable you added to `updateAxes`. Perhaps that could be passed in as the argument to `updateAxes` instead of `notAnimated`? Then the transition time would be configurable, and you could still pass in `0` to transition instantly instead of `true`.

**Comment by dehli** [comment]
Thanks a lot @syntagmatic! I like the idea of having `transitionTime` configurable. I'll go ahead and modify this pull request so that it uses that instead. I'll comment again when I have that new version implemented.

**Comment by dehli** [comment]
@syntagmatic Hello, I made the changes! All the whitespace diffs are either trailing whitespace or from swapping tabs with spaces. I updated the README as well. Thoughts?

**Comment by dehli** [comment]
I messed something up on my fork... I'm going to retry this :)

**Pull request closed without merging**
