### PR TITLE
null value handling

### PR DESCRIPTION
**Pull request by Git-me-outta-here**
Null values are handled as described in Templ et at. 2012, "Exploring incomplete data using visualization techniques". To represent a null value, the path is drawn away from an axis. A horizontal line separates null values from observed data.

Usage: Set the nullValueSeparator to "top" or "bottom". Optionally set top and bottom paddings in nullValueSeparatorPadding.

compare example "nullValues.html"

### CODE REVIEW

**Comment by Git-me-outta-here** [comment]
I see there is another pull request to **handle null values** as well as one to **set 1D brushes**.

Are you still active? Please pick a solution or tell me how to improve mine!

Cheers,
Git-me-outta-here

**Comment by syntagmatic** [comment]
I'm listening in here and working on parallel coordinates examples, but I don't have the headspace to keep up with development and evaluate non-trivial pull requests. The latest technique I'm using for handling null values is captured in this example:

http://bl.ocks.org/syntagmatic/0d1635533f6fb5ac4da3

@Git-me-outta-here I've added you as a collaborator to this repo. 

cc @julianheinrich @bbroeksema

**Comment by Git-me-outta-here** [comment]
I'm merging my code now.
Two new examples:
nullValues.html shows how to use the optional null line, which separates the null values
setterForBrushes.html can set a (1D) brush

**Comment by julianheinrich** [comment]
Thanks @Git-me-outta-here.
In the future, please don't merge multiple features at once. Also, @bbroeksema has written up a nice workflow for contributors on how to develop and merge new features [here](https://github.com/bbroeksema/writing/blob/master/parcoords-git-workflow.md)

I'll add this to the README as well for future collaborators.

As for setting brush extents:
wasn't that already fixed in #126 ?

We now have two functions for this: brushExtents() and setBrushExtents.
Anyone tested the solution merged by @mcwillso in #126?

**Comment by mcwillso** [comment]
Yes I tested #126 with 1d and 1d-multi. And #126 follows other standards for reusing a function to set/get which I think is preferred.

I was going to compare the two different null value pull requests(#73 and #128) just haven't had time.  After looking at the #128 example http://syntagmatic.github.io/parallel-coordinates/examples/nullValues.html this is not the appropriate solution(drawing null values below the lowest axis value).

**Comment by julianheinrich** [comment]
I see. What's the syntax for 1D-multi? I was trying to use that in your example but it didn't work (just adding d3.multibrush.svg and changing to brushmode '1D-axes-multi'

**Comment by mcwillso** [comment]
Usage for http://syntagmatic.github.io/parallel-coordinates/examples/brushing.html in dev console would be:
parcoords.brushExtents({"cylinders": [5,7]});

**Comment by julianheinrich** [comment]
that works fine thanks, but how to add *multiple* brushes on the same axis?
In the above example,
```
parcoords.brushExtents({"cylinders": [3,4], "cylinders": [7,8]});
```

doesn't work

**Comment by julianheinrich** [comment]
that works fine for 1D, but not for 1D-multi. Am I missing sth?

**Comment by mcwillso** [comment]
Ah.  In #256 I ensured that the multi axis was working.  It does appear that multi-axis programmatic brushing isn't working. I can get that fixed.  Syntax should be
```
parcoords.brushExtents({"cylinders": [[1,2][4,5]]}
```

**Comment by Git-me-outta-here** [comment]
oh I see, your setter for brush extents is indeed better. I had not even considered 1D-multi.

For the null value handling, I much prefer the Templ solution. Interrupting lines makes it impossible to follow them. Also, a data point with a valid value on the first dimension but a null value on the second dimension could not draw anything on the first dimension.

sorry about the merge confusion, that was my first contribution to github.

**Comment by syntagmatic** [comment]
Thanks @Git-me-outta-here for the contributions. No worries about the git issues... @bbroeksema had to put that guide together because I myself was mucking up the git history!

I'm somewhat torn on this issue. When we're interested in nulls, this is a great way to treat them. Perhaps it could use a "null" label on the bottom row somewhere to help the viewer understand why values extend below the chart.

For many common cases, I agree with @mcwillso on this. I don't think Templ's solution is desirable as a default is because it creates meaningless intersections between axes. For two adjacent quantitative dimensions, the patterns and intersections of the lines are significant. From a geometric perspective, there's not a defensible place to put nulls... anywhere!

Here's an image with my opinion for a decent default behavior for nulls that ensures all non-null values are rendered.

screen shot 2016-01-14 at 1 34 23 am

Example here: http://bl.ocks.org/syntagmatic/0d1635533f6fb5ac4da3

In the space between two null values, nothing is rendered. But if there's a value next to a null dimension, a small horizontal line is drawn. This makes the values for this food (Falafel, if you're curious) visible on the Protein and Total Lipid dimensions, even though those values and sandwiched by nulls. Yet Templ's solution is better than rendering nulls as 0, which I think is the current behavior (in the original D3 examples as well). Of all the options, that is the worst for analysis because it collapses real data values with nulls.

I think a major problem here is that the library isn't well-factored to provide different rendering modes. Data quality analysis is a major use case and it would be great to support both techniques.

**Comment by syntagmatic** [comment]
Correction, I'm totally clueless.

The null value rendering is configured using `{nullValueSeparator: "bottom"}`, so it's not a default at all.

It may be that some optional rendering modes are incompatible with some brushing modes. I'm okay with that. Perhaps just make a note of the incompatibility in the documentation for `nullValueSeparator`?

**Comment by Git-me-outta-here** [comment]
Should we make your solution (little marks show up for points sandwiched by nulls) the default? Its not yet in the master, is it? For some tasks the null value separator is definitely useful, so we can keep it optional.

Which brushing modes do not work with the separator?

**Comment by jmgelman** [comment]
@mcwillso I attempted to add your solution for setting brush extents to 1D-multi.js in my fork [4a0fe82](https://github.com/jmgelman/parallel-coordinates/commit/4a0fe82a69ccded24c6d60be0c4b1e87739a4c88). It seems to work with the syntax you described above, but I'm getting the `d3_transitionInheritId` error in the console. Do you by chance know where the cause of this is coming from?

**Comment by mcwillso** [comment]
@jmgelman This is from an old version of [d3.svg.multibrush](https://github.com/humanitiesplusdesign/d3.svg.multibrush), we need to update the source to include the latest.

**Pull request merged**
